### ISSUE TITLE
RefOS compile errors

### ISSUE THREAD

**Issue by jm--** [seL4/refos-manifest#1]
I tried to compile RefOS following the instructions, but it seems there are currently at least two issues.

First, running make (step 7) fails with error:
make: **\* No rule to make target 'file_server', needed by `./build/x86/pc99/process_server/archive.o'.  Stop.

My current workaround is:
1) Add `lib-dirs:=libs` to ./Makefile.

2) Create a ./Kbuild file with:

```
-include $(wildcard apps/*/Kbuild)
-include $(wildcard libs/*/Kbuild)
```

It could be that the problem started when  [this](https://github.com/seL4/common-tool/commit/7f016c43ea8ad2ce6b9d3536ee76740ef668e85e#diff-2d427f41aada9237cc25bd11a48904ee) commit removed the following from ./tools/common/project.mk.

```
ifeq ($(old-kbuild-hack), 1)
    include $(SEL4_APPS_PATH)/Kbuild
endif
```

---

Second, I had to run something like the following because of the changes from ia32 to x86 [here](https://github.com/seL4/seL4/commit/914741ea3357b88c4995ff6c98e9aba913f6f044), I guess. 

```
mv libs/libmuslc/arch_include/ia32 libs/libmuslc/arch_include/x86
mv ./apps/tetris/crt/arch-ia32 ./apps/tetris/crt/arch-x86
mv ./apps/snake/crt/arch-ia32 ./apps/snake/crt/arch-x86
mv ./apps/process_server/crt/arch-ia32 ./apps/process_server/crt/arch-x86
mv ./apps/console_server/crt/arch-ia32 ./apps/console_server/crt/arch-x86
mv ./apps/timer_server/crt/arch-ia32 ./apps/timer_server/crt/arch-x86
mv ./apps/terminal/crt/arch-ia32 ./apps/terminal/crt/arch-x86
mv ./apps/test_os/crt/arch-ia32 ./apps/test_os/crt/arch-x86
mv ./apps/file_server/crt/arch-ia32 ./apps/file_server/crt/arch-x86
mv ./apps/selfloader/crt/arch-ia32 ./apps/selfloader/crt/arch-x86
mv ./apps/nethack/crt/arch-ia32 ./apps/nethack/crt/arch-x86
mv ./apps/test_user/crt/arch-ia32 ./apps/test_user/crt/arch-x86
```

**Comment by hypernewbie** [comment]
Can you please create a pull request? I will review it.

**Comment by jm--** [comment]
Done. I created 3 PRs, as the proposed fix affects 3 repos. (A PR cannot span multiple repos, right?)
Thanks, Josef

**Comment by hypernewbie** [comment]
thanks; I will review the 2 refos changes over next few days.
