### ISSUE TITLE
compile fail, lots of compile error.

### ISSUE THREAD

**Issue by bestming8** [seL4/refos-manifest#11]
1. repo undownloadable
I fixed it by using "repo init -u https://git@github.com/seL4/refos-manifest"

2. so many compile errors
just list a few.

* libs/librefos/src/refos-rpc/rpc.c:326: undefined reference to `seL4_CapData_Badge_get_Badge'

* apps/timer_server/src/device_timer.c:345:21: error: request for member ‘properties’ in something not a structure or union
     if (!s->timerDev->properties.upcounter) {
* stage/arm/imx31/include/refos-rpc/data_client_helper.h:176:16: error: ‘EINVALIDPARAM’ undeclared (first use in this function)
stage/arm/imx31/include/refos-rpc/data_client_helper.h:179:16: error: ‘ENOPARAMBUFFER’ undeclared (first use in this function)

....

Author, can u take some time to fix all of them, I am interested this project. Thanks

**Comment by pingerino** [comment]
You need to use "repo init - u repo init -u https://git@github.com/seL4/refos-manifest -m working.xml", which is frozen to revisions that build.

default.xml points to the tips of each repo, which will not compile as this project is not currently maintained.
