### ISSUE TITLE
repo init fails

### ISSUE THREAD

**Issue by ssoloski** [seL4/refos-manifest#7]
Trying to follow steps in quickstart - but get error when running repo init command:

repo init -u ssh://git@github.com/seL4/refos-manifest -b master

Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
Get ssh://git@github.com/seL4/refos-manifest
Permission denied (publickey).
Permission denied (publickey).
fatal: Could not read from remote repository.

I've built and run the camkeys demo without problems, but am unable to get the refos project.

**Comment by wom-bat** [comment]
This implies you haven;'t installed an SSH key on github.  Try using
`   repo init -u https://github.com/seL4/refos-manifest -b master`
instead of the ssh URI

**Comment by ssoloski** [comment]
Doh! 
Thx - the https: version worked like a charm.
