### ISSUE TITLE
seL4_CapData_Badge_new(badge) is deprecated

### ISSUE THREAD

**Issue by AslamAlvi** [seL4/refos-manifest#8]
In file included from  libs/librefos/src/sync.c:22:0:
         seL4_AllRights, seL4_CapData_Badge_new(badge)
this function is deprecated 
and because of it I wont be able to build refos.
Any workaround for it?
Please Help

**Comment by AdrianDanis** [comment]
@AslamAlvi You can still use deprecated functions, you will just get a warning and they will eventually get removed. Long term you can see the [upgrade notes in the CHANGES file](https://github.com/seL4/seL4/blob/master/CHANGES#L22) for how to update.

**Comment by AslamAlvi** [comment]
Thanks  a lot I will try that
