### ISSUE TITLE
undefined reference to `seL4_CapData_Badge_get_Badge'

### ISSUE THREAD

**Issue by AslamAlvi** [seL4/refos-manifest#9]
Hello All,
Greetings,

I have just started studying  seL4 and i  was building the RefOS but while building i got this error in linking of seL4_CapData_Badge_get_Badge function.

undefined reference to `seL4_CapData_Badge_get_Badge'
/stage/arm/imx31/lib/librefos.a(rpc.o): In function `rpc_sv_pop_cptr':
libs/librefos/src/refos-rpc/rpc.c:328: undefined reference to `seL4_CapData_Badge_get_Badge'
collect2: error: ld returned 1 exit status
/stage/arm/imx31/common/common.mk:307: recipe for target 'file_server.elf' failed

Please suggest me to resolve this issue .

Thank You in Advance 
Aslam

**Comment by AslamAlvi** [comment]
@AdrianDanis  May you help with this  undefined reference of seL4_CapData_Badge_get_Badge?
or any workaround for it ?

**Comment by AdrianDanis** [comment]
Hi @AslamAlvi. I referenced the [upgrade notes in the CHANGES file](https://github.com/seL4/seL4/blob/master/CHANGES#L22) in [replying](https://github.com/seL4/refos-manifest/issues/8#issuecomment-348390847) to your [previous issue](https://github.com/seL4/refos-manifest/issues/8). As it says in the CHANGES file the badge is now just a `seL4_Word`, which is a plain old data type, so there is no need to attempt to extract the badge out of your data. Whatever you have is already the badge.

**Comment by AslamAlvi** [comment]
Hi @AdrianDanis  thanks for your reply and your support i was able to build the refOS now 
Thanks alot
